### ISSUE TITLE
Use_latex preamble issue

### ISSUE THREAD

**Issue by syncrostone** [mwshinn/CanD#12]
I get the following error when doing `c.use_latex(preamble=r'\usepackage{bm}')`

`/scratch/jts58/devenv/lib/python3.7/site-packages/CanD-0.0.1-py3.7.egg/cand/canvas.py:698: UserWarning: FixedFormatter should only be used together with FixedLocator
  ax.set_yticklabels(labels)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-6486f3e3d556> in <module>
    104 
    105 
--> 106 make_figure()

<ipython-input-5-6486f3e3d556> in make_figure()
     98         c.add_figure_labels([(chr(ord('A')+i), plot_names[i]) ])
     99         c.ax(plot_names[i]).set_title(titles[i])
--> 100     c.show()
    101     c.save("../ThesisLatex/Chapter1/Figs/Raster/gp_intro.png", dpi=300)
    102     c.save("../ThesisLatex/Chapter1/Figs/Vector/gp_intro.pdf")

/scratch/jts58/devenv/lib/python3.7/site-packages/CanD-0.0.1-py3.7.egg/cand/canvas.py in show(self, **kwargs)
   1008         if in_jupyter and 'transparent' not in kwargs.keys():
   1009             kwargs['transparent'] = False
-> 1010         self.save(tmp, **kwargs)
   1011         # Display, either in a new window, or in Jupyter
   1012         if in_jupyter:

/scratch/jts58/devenv/lib/python3.7/site-packages/paranoid/decorators.py in _decorated(*args, **kwargs)
    124         _check_accepts(func, argvals)
    125         _check_requires(func, argvals)
--> 126         returnvalue = func(*args, **kwargs)
    127         _check_returns(func, returnvalue)
    128         _check_ensures(func, returnvalue, argvals)

/scratch/jts58/devenv/lib/python3.7/site-packages/CanD-0.0.1-py3.7.egg/cand/canvas.py in save(self, filename, dpi, *args, **kwargs)
    806             if self.latex_preamble is not None:
    807                 preamble = matplotlib.rcParams.setdefault('pgf.preamble', [])
--> 808                 preamble.append(self.latex_preamble)
    809         elif self.backend == "default":
    810             from matplotlib.backends.backend_agg import FigureCanvasAgg

AttributeError: 'str' object has no attribute 'append'`

**Comment by syncrostone** [comment]
Now I get the below error, it seems like the preamble hasn't been compiled when print_pgf is called, which seems to use the preamble?

`
---------------------------------------------------------------------------
LatexError                                Traceback (most recent call last)
/scratch/jts58/devenv/lib/python3.7/site-packages/matplotlib/backends/backend_pgf.py in get_width_height_descent(self, text, prop)
    346         try:
--> 347             self._expect_prompt()
    348         except LatexError as e:

/scratch/jts58/devenv/lib/python3.7/site-packages/matplotlib/backends/backend_pgf.py in _expect_prompt(self)
    269     def _expect_prompt(self):
--> 270         return self._expect("\n*")
    271 

/scratch/jts58/devenv/lib/python3.7/site-packages/matplotlib/backends/backend_pgf.py in _expect(self, s)
    265                 self.latex = None
--> 266                 raise LatexError("LaTeX process halted", "".join(chars))
    267         return "".join(chars)

LatexError: LaTeX process halted

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
<ipython-input-4-6486f3e3d556> in <module>
    104 
    105 
--> 106 make_figure()

<ipython-input-4-6486f3e3d556> in make_figure()
     98         c.add_figure_labels([(chr(ord('A')+i), plot_names[i]) ])
     99         c.ax(plot_names[i]).set_title(titles[i])
--> 100     c.show()
    101     c.save("../ThesisLatex/Chapter1/Figs/Raster/gp_intro.png", dpi=300)
    102     c.save("../ThesisLatex/Chapter1/Figs/Vector/gp_intro.pdf")

/scratch/jts58/devenv/lib/python3.7/site-packages/CanD-0.0.1-py3.7.egg/cand/canvas.py in show(self, **kwargs)
   1008         if in_jupyter and 'transparent' not in kwargs.keys():
   1009             kwargs['transparent'] = False
-> 1010         self.save(tmp, **kwargs)
   1011         # Display, either in a new window, or in Jupyter
   1012         if in_jupyter:

/scratch/jts58/devenv/lib/python3.7/site-packages/paranoid/decorators.py in _decorated(*args, **kwargs)
    124         _check_accepts(func, argvals)
    125         _check_requires(func, argvals)
--> 126         returnvalue = func(*args, **kwargs)
    127         _check_returns(func, returnvalue)
    128         _check_ensures(func, returnvalue, argvals)

/scratch/jts58/devenv/lib/python3.7/site-packages/CanD-0.0.1-py3.7.egg/cand/canvas.py in save(self, filename, dpi, *args, **kwargs)
    811             mplcanvas = FigureCanvasAgg(self.figure)
    812         with matplotlib.rc_context(rc=self.localRc):
--> 813             self.figure.savefig(filename, dpi=dpi, *args, **kwargs)
    814         if filetype == "png":
    815             with Image.open(filename) as img:

/scratch/jts58/devenv/lib/python3.7/site-packages/matplotlib/figure.py in savefig(self, fname, transparent, **kwargs)
   2309                 patch.set_edgecolor('none')
   2310 
-> 2311         self.canvas.print_figure(fname, **kwargs)
   2312 
   2313         if transparent:

/scratch/jts58/devenv/lib/python3.7/site-packages/matplotlib/backend_bases.py in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, pad_inches, bbox_extra_artists, backend, **kwargs)
   2215                     orientation=orientation,
   2216                     bbox_inches_restore=_bbox_inches_restore,
-> 2217                     **kwargs)
   2218             finally:
   2219                 if bbox_inches and restore_bbox:

/scratch/jts58/devenv/lib/python3.7/site-packages/matplotlib/backends/backend_pgf.py in print_png(self, fname_or_fh, *args, **kwargs)
    951             return
    952         with cbook.open_file_cm(fname_or_fh, "wb") as file:
--> 953             self._print_png_to_fh(file, *args, **kwargs)
    954 
    955     def get_renderer(self):

/scratch/jts58/devenv/lib/python3.7/site-packages/matplotlib/backends/backend_pgf.py in _print_png_to_fh(self, fh, *args, **kwargs)
    934             fname_png = os.path.join(tmpdir, "figure.png")
    935             # create pdf and try to convert it to png
--> 936             self.print_pdf(fname_pdf, *args, **kwargs)
    937             converter(fname_pdf, fname_png, dpi=self.figure.dpi)
    938             # copy file contents to target

/scratch/jts58/devenv/lib/python3.7/site-packages/matplotlib/backends/backend_pgf.py in print_pdf(self, fname_or_fh, *args, **kwargs)
    923             return
    924         with cbook.open_file_cm(fname_or_fh, "wb") as file:
--> 925             self._print_pdf_to_fh(file, *args, **kwargs)
    926 
    927     def _print_png_to_fh(self, fh, *args, **kwargs):

/scratch/jts58/devenv/lib/python3.7/site-packages/matplotlib/backends/backend_pgf.py in _print_pdf_to_fh(self, fh, metadata, *args, **kwargs)
    884 
    885             # print figure to pgf and compile it with latex
--> 886             self.print_pgf(fname_pgf, *args, **kwargs)
    887 
    888             latex_preamble = get_preamble()

/scratch/jts58/devenv/lib/python3.7/site-packages/matplotlib/backends/backend_pgf.py in print_pgf(self, fname_or_fh, *args, **kwargs)
    867             if not cbook.file_requires_unicode(file):
    868                 file = codecs.getwriter("utf-8")(file)
--> 869             self._print_pgf_to_fh(file, *args, **kwargs)
    870 
    871     def _print_pdf_to_fh(self, fh, *args, metadata=None, **kwargs):

/scratch/jts58/devenv/lib/python3.7/site-packages/matplotlib/backend_bases.py in wrapper(*args, **kwargs)
   1637             kwargs.pop(arg)
   1638 
-> 1639         return func(*args, **kwargs)
   1640 
   1641     return wrapper

/scratch/jts58/devenv/lib/python3.7/site-packages/matplotlib/cbook/deprecation.py in wrapper(*inner_args, **inner_kwargs)
    409                          else deprecation_addendum,
    410                 **kwargs)
--> 411         return func(*inner_args, **inner_kwargs)
    412 
    413     return wrapper

/scratch/jts58/devenv/lib/python3.7/site-packages/matplotlib/backends/backend_pgf.py in _print_pgf_to_fh(self, fh, dryrun, bbox_inches_restore)
    849                                      RendererPgf(self.figure, fh),
    850                                      bbox_inches_restore=bbox_inches_restore)
--> 851         self.figure.draw(renderer)
    852 
    853         # end the pgfpicture environment

/scratch/jts58/devenv/lib/python3.7/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     39                 renderer.start_filter()
     40 
---> 41             return draw(artist, renderer, *args, **kwargs)
     42         finally:
     43             if artist.get_agg_filter() is not None:

/scratch/jts58/devenv/lib/python3.7/site-packages/matplotlib/figure.py in draw(self, renderer)
   1862             self.patch.draw(renderer)
   1863             mimage._draw_list_compositing_images(
-> 1864                 renderer, self, artists, self.suppressComposite)
   1865 
   1866             renderer.close_group('figure')

/scratch/jts58/devenv/lib/python3.7/site-packages/matplotlib/image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    129     if not_composite or not has_images:
    130         for a in artists:
--> 131             a.draw(renderer)
    132     else:
    133         # Composite any adjacent images together

/scratch/jts58/devenv/lib/python3.7/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     39                 renderer.start_filter()
     40 
---> 41             return draw(artist, renderer, *args, **kwargs)
     42         finally:
     43             if artist.get_agg_filter() is not None:

/scratch/jts58/devenv/lib/python3.7/site-packages/matplotlib/cbook/deprecation.py in wrapper(*inner_args, **inner_kwargs)
    409                          else deprecation_addendum,
    410                 **kwargs)
--> 411         return func(*inner_args, **inner_kwargs)
    412 
    413     return wrapper

/scratch/jts58/devenv/lib/python3.7/site-packages/matplotlib/axes/_base.py in draw(self, renderer, inframe)
   2705                 artists.remove(spine)
   2706 
-> 2707         self._update_title_position(renderer)
   2708 
   2709         if not self.axison or inframe:

/scratch/jts58/devenv/lib/python3.7/site-packages/matplotlib/axes/_base.py in _update_title_position(self, renderer)
   2646                 _log.debug('top of axes not in the figure, so title not moved')
   2647                 return
-> 2648             if title.get_window_extent(renderer).ymin < top:
   2649                 _, y = self.transAxes.inverted().transform((0, top))
   2650                 title.set_position((x, y))

/scratch/jts58/devenv/lib/python3.7/site-packages/matplotlib/text.py in get_window_extent(self, renderer, dpi)
    900 
    901         with cbook._setattr_cm(self.figure, dpi=dpi):
--> 902             bbox, info, descent = self._get_layout(self._renderer)
    903             x, y = self.get_unitless_position()
    904             x, y = self.get_transform().transform((x, y))

/scratch/jts58/devenv/lib/python3.7/site-packages/matplotlib/text.py in _get_layout(self, renderer)
    294             if clean_line:
    295                 w, h, d = renderer.get_text_width_height_descent(
--> 296                     clean_line, self._fontproperties, ismath=ismath)
    297             else:
    298                 w = h = d = 0

/scratch/jts58/devenv/lib/python3.7/site-packages/matplotlib/backends/backend_pgf.py in get_text_width_height_descent(self, s, prop, ismath)
    737         # get text metrics in units of latex pt, convert to display units
    738         w, h, d = (LatexManager._get_cached_or_new()
--> 739                    .get_width_height_descent(s, prop))
    740         # TODO: this should be latex_pt_to_in instead of mpl_pt_to_in
    741         # but having a little bit more space around the text looks better,

/scratch/jts58/devenv/lib/python3.7/site-packages/matplotlib/backends/backend_pgf.py in get_width_height_descent(self, text, prop)
    348         except LatexError as e:
    349             raise ValueError("Error processing '{}'\nLaTeX Output:\n{}"
--> 350                              .format(text, e.latex_output)) from e
    351 
    352         # typeout width, height and text offset of the last textbox

ValueError: Error processing '\(\displaystyle \bm \Sigma\) with \(\displaystyle \ell=.1\)'
LaTeX Output:
! Undefined control sequence.
<argument> ...000}\selectfont \(\displaystyle \bm 
                                                  \Sigma \) with \(\displays...
<*> ...bm \Sigma\) with \(\displaystyle \ell=.1\)}
                                                  
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on texput.log.
`

**Comment by mwshinn** [comment]
That should fix this one.  Thanks for all of these bug reports you've been submitting recently, they're very helpful!

**Comment by syncrostone** [comment]
This works, thank you! I get the following warning, not sure how to interpret it:
canvas.py:698: UserWarning: FixedFormatter should only be used together with FixedLocator

**Comment by mwshinn** [comment]
This commit should do it!
