### ISSUE TITLE
Text cannot be rotated

### ISSUE THREAD

**Issue by jankaWIS** [mwshinn/CanD#15]
I'm sorry if I missed something but I cannot find it in the docs nor in the `c.add_text()` help. How can I rotate text? I mean in [this way](https://matplotlib.org/stable/gallery/text_labels_and_annotations/text_rotation.html), eg. by adding a `rotation` keyword. Thanks.

**Comment by mwshinn** [comment]
You can use the "rotation" keyword!  In fact, you can use any keyword supported by [matplotlib.text](https://matplotlib.org/stable/api/text_api.html#matplotlib.text.Text).  I just committed c0703f3479c29da8b45d6f7c0a09e411e65aab77 as an update which documents this explicitly.

**Comment by jankaWIS** [comment]
Maybe it was because of my outdated version, now it works perfectly, thanks!
