### ISSUE TITLE
x-axis labels go out of picture if rotated

### ISSUE THREAD

**Issue by jankaWIS** [mwshinn/CanD#16]
Hi,

If the plot has some x labels that are long and rotated, they go out of the picture and there is no obvious way to squeeze them in. Changing the y-axis limits also doesn't work - it zooms in in the graph but the relative space for the labels does not change. How can I squeeze the information there?

```python
from cand import Canvas, Vector, Point
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

tmp = pd.DataFrame({
    'labels': ['my_first_label', 'my_second_label', 'another'],
    'values_mean': [5,6,7],
    'values_std': [0.5, 0.4, 0.6],
})


# CanD
a = 14
b = 10
c = Canvas(a, b, "cm")

# set font
c.set_font("Arial", size=10)

# letters
c.add_text("A)", Point(.05, 0.98), weight="bold")

### GRID
c.add_grid(["barplot"], 1, Point(2, 1, "cm"),  Point(a-.5,  b-1, "cm"), spacing=Vector(.5, 2.5, "cm"))

# plot
c.axes["barplot"].bar(tmp['labels'], tmp['values_mean'], yerr=tmp['values_std'])

# change labels and rotation
c.axes["barplot"].set_xticks(list(c.axes["barplot"].get_xticks()))
c.axes["barplot"].set_xticklabels([x.replace('_', ' ') for x in tmp['labels'].values], rotation=90, ha='center')

# this does not help
# c.axes["barplot"].set_ylim(2,8)
    

c.show()
```

![image](https://user-images.githubusercontent.com/54404810/208600463-ac0665d0-b112-4179-b054-abef85fc395e.png)

**Comment by mwshinn** [comment]
You need to change the position of the bottom of the axis.  Switching the 1 to a 3 does the trick, as so:

```
### GRID
c.add_grid(["barplot"], 1, Point(2, 3, "cm"),  Point(a-.5,  b-1, "cm"), spacing=Vector(.5, 2.5, "cm"))
```

By the way, you can also access the axis with `c.ax("barplot")` instead of `c.axes["barplot"]`, and you can use `add_axis` instead of `add_grid` if there is only one axis.

**Comment by jankaWIS** [comment]
Right, that works. Sorry for being vague. The issue I meant is that now if I add a longer text, maybe I will need to switch it from 1 to 5 because 1 to 3 won't be enough. So in some sense, there is a lot of going back and forth, unlike in matplotlib, where you can do this and it'll automatically resize the figure to fit the space.

> and you can use add_axis instead of add_grid if there is only one axis.

Yeah, I adapted a code where I have more figures and this was the easiest for me. But thanks for the other tip :).

**Comment by mwshinn** [comment]
Unfortunately CanD doesn't do automatic positioning or sizing.  Matplotlib's automatic layouts can cause inconsistency between figures, so CanD provides the opposite approach of making all positioning decisions explicit.
